# <center> Aplicación en Bioestadística: Análisis de Depresión en RR.SS.
## <center>AI Saturdays Euskadi Donostia 2020

In [96]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

**Read data into a Pandas DataFrame**

In [97]:
data = pd.read_csv('OSF_socialmedia_data.csv')
data.head()

,Unnamed: 0,Participant,Date,Day,Time,Session.Name,Notification.No,LifePak.Download.No,Responded,Completed.Session,...,Loneliness,Concentrat,LossOfInt,Inferior,Hopeless,Stress,PSMU,AutoPSMU,News,Active
0,1,115091,05/02/2017,Tuesday,10:00:06,Daily questions,1,1,1,1,...,61.0,64.0,68.0,50.0,56.0,73.0,66.0,66,39.0,38.0
1,2,115091,05/02/2017,Tuesday,12:02:48,Daily questions,2,1,1,1,...,57.0,70.0,58.0,37.0,56.0,67.0,0.0,#skipped#,27.0,23.0
2,3,115091,05/02/2017,Tuesday,14:03:02,Daily questions,3,1,1,1,...,44.0,70.0,67.0,26.0,38.0,39.0,63.0,56,34.0,36.0
3,4,115091,05/02/2017,Tuesday,16:34:28,Daily questions,4,1,1,1,...,56.0,79.0,89.0,30.0,20.0,60.0,67.0,68,29.0,23.0
4,5,115091,05/02/2017,Tuesday,18:00:00,Daily questions,5,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
data.shape

(12245, 26)

In [99]:
nullcol = data.columns[data.isna().any()]
nullsum = data[nullcol].isna().sum()
responded = data['Responded'].value_counts()
print('{} sessions answered, {} left without answer \n'.format(responded[1],responded[0]))
print(nullsum)
print("\n Dentro de las sesiones que sí se han contestado, hay valores nulos")

8695 sessions answered, 3550 left without answer

Session.Instance                    3550
Session.Instance.Response.Lapse     3550
Instr_DQs                          12245
Fatigue                             3592
DeprMood                            3597
Loneliness                          3599
Concentrat                          3600
LossOfInt                           3599
Inferior                            3599
Hopeless                            3595
Stress                              3596
PSMU                                3599
AutoPSMU                            3594
News                                3598
Active                              3600
dtype: int64

 Dentro de las sesiones que sí se han contestado, hay valores nulos

In [114]:
#De este modo tendremos un dataframe sin las sesiones sin contestar
answered = data.loc[:, 'Responded'] == 1
cleaned_data = data.loc[answered]

#Pasemos a ver cuantos valores nulos tenemos dentro de las sesiones contestadas
nullcol = cleaned_data.columns[cleaned_data.isna().any()]
nullsum = cleaned_data[nullcol].isna().sum()
print('Nulos en el dataset limpio \n {}'.format(nullsum))

#Vamos a ver los valores del dataset
print('\n Valores del dataset limpio \n')
surveydata = cleaned_data.iloc[:,14:]
surveycolumns = surveydata.columns
for col in surveycolumns:
    print(cleaned_data[col].value_counts())
    print(cleaned_data[col].value_counts(normalize=True)[0])
    print()
#¿Muchos ceros?¿Normal?

Nulos en el dataset limpio
 Instr_DQs     8695
Fatigue         42
DeprMood        47
Loneliness      49
Concentrat      50
LossOfInt       49
Inferior        49
Hopeless        45
Stress          46
PSMU            49
AutoPSMU        44
News            48
Active          50
dtype: int64

 Valores del dataset limpio

0.0     1426
20.0     140
62.0     140
68.0     134
19.0     134
        ...
95.0      11
97.0      11
48.0      10
99.0       9
96.0       6
Name: Fatigue, Length: 101, dtype: int64
0.16479833583728187

0.0     3484
1.0      185
14.0     183
13.0     181
11.0     169
        ...
86.0       1
90.0       1
88.0       1
97.0       1
81.0       1
Name: DeprMood, Length: 97, dtype: int64
0.4028677150786309

0.0     3620
1.0      192
12.0     174
8.0      174
16.0     172
        ...
84.0       1
81.0       1
90.0       1
96.0       1
95.0       1
Name: Loneliness, Length: 96, dtype: int64
0.41869072403423546

0.0     2045
17.0     173
16.0     172
19.0     168
20.0     164
        ...
87.0       4
99.0       4
94.0       4
96.0       3
97.0       2
Name: Concentrat, Length: 101, dtype: int64
0.23655292076344708

0.0     2178
19.0     164
13.0     156
14.0     156
16.0     153
        ...
95.0       5
94.0       5
98.0       4
96.0       3
99.0       3
Name: LossOfInt, Length: 101, dtype: int64
0.25190839694656486

0.0     3862
1.0      207
14.0     194
11.0     186
2.0      173
        ...
85.0       1
86.0       1
96.0       1
90.0       1
49.0       1
Name: Inferior, Length: 95, dtype: int64
0.44668054591718714

0.0     3553
1.0      222
13.0     189
15.0     179
14.0     177
        ...
86.0       1
82.0       1
88.0       1
98.0       1
90.0       1
Name: Hopeless, Length: 93, dtype: int64
0.4107514450867052

0.0     2561
11.0     173
13.0     167
20.0     166
10.0     165
        ...
99.0       2
94.0       2
93.0       1
91.0       1
95.0       1
Name: Stress, Length: 100, dtype: int64
0.296103595791421

0.0     2231
65.0     122
62.0     119
61.0     118
72.0     117
        ...
91.0       6
96.0       6
95.0       4
98.0       3
99.0       1
Name: PSMU, Length: 101, dtype: int64
0.2580383992597733

#skipped#    1859
0            1289
15            118
14            117
25            114
             ...
95              4
94              2
97              2
93              1
98              1
Name: AutoPSMU, Length: 102, dtype: int64
0.21488845220205757

0.0     3041
14.0     152
21.0     142
20.0     138
16.0     132
        ...
90.0       3
93.0       3
97.0       2
99.0       1
92.0       1
Name: News, Length: 100, dtype: int64
0.35168266450792185

0.0     3025
16.0     144
14.0     138
1.0      136
10.0     134
        ...
97.0       2
92.0       2
95.0       2
98.0       1
94.0       1
Name: Active, Length: 100, dtype: int64
0.3499132446500868